# frozen_string_literal: true

RSpec.describe RubocopTodoCorrector::Commands::Describe do
  describe '.call' do
    subject do
      described_class.call(
        cop_name: 'Style/StringLiterals',
        temporary_gemfile_path: 'tmp/Gemfile_rubocop_todo_corrector.rb'
      )
    end

    before do
      allow(Kernel).to receive(:puts)
    end

    context 'with valid condition' do
      it 'returns cop name' do
        subject
        expect(Kernel).to have_received(:puts).with(
          <<~'MARKDOWN'
            ## Summary

            Auto-corrected [Style/StringLiterals](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/StringLiterals).

            ## Details

            ### Style/StringLiterals

            > Checks if uses of quotes match the configured preference.
            >
            > #### Examples
            >
            > EnforcedStyle: single_quotes (default)
            >
            > ```ruby
            > # bad
            > "No special symbols"
            > "No string interpolation"
            > "Just text"
            >
            > # good
            > 'No special symbols'
            > 'No string interpolation'
            > 'Just text'
            > "Wait! What's #{this}!"
            > ```
            >
            > EnforcedStyle: double_quotes
            >
            > ```ruby
            > # bad
            > 'Just some text'
            > 'No special chars or interpolation'
            >
            > # good
            > "Just some text"
            > "No special chars or interpolation"
            > "Every string in #{project} uses double_quotes"
            > ```

            ### Note

            This pull request was generated by [rubocop_todo_corrector](https://github.com/r7kamura/rubocop_todo_corrector).
          MARKDOWN
        )
      end
    end
  end
end
